# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - devel/python_bindings
      - devel/refactor_pybind11
      - devel/test_parse
      - fix/correct_parse      - 
  pull_request:
    branches:
      - master
      - devel/python_bindings
      - fix/correct_parse
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
  
    # Install dependencies
    - name: Installing pytest
      run: pip install pytest
      
    # Test
    - name: Changing directory and running tests
      run: |
        cd bindings/python
        pytest
